dist: xenial
language: python
python:
  - 3.7

before_install:
  - sudo add-apt-repository --yes ppa:retorquere/zotero
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install zotero jurism
  - travis_retry ./check-latest-zotero.py

cache:
  npm: true
  bundler: true
  pip: true
  apt: true
  directories:
  - node_modules
  - .cache/pip

script: |
  #set -e
  #set -x

  #git submodule sync && git submodule update --init --recursive
  if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]] || [[ ! -z "$TRAVIS_TAG" ]] || [[ "$TRAVIS_COMMIT_MESSAGE" == *"#nightly"* ]]; then
    export TAGLIMIT=""
    export TIMEOUT=300
  else
    export TAGLIMIT="and not @nightly"
    export TIMEOUT=60
  fi

  npm run build

  # https://github.com/travis-ci/travis-ci/issues/8920
  # https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
  # something to do with node?
  python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
  python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
  python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print(flags&os.O_NONBLOCK);'

  xvfb-run behave --define zotero=$ZOTERO --define timeout=$TIMEOUT --tags="$CLUSTER $TAGLIMIT"

after_failure:
  curl -F "file=@~/.BBTZ5TEST.log" https://file.io

jobs:
  include:
  - stage: test
    env:
    - ZOTERO=zotero
    - CLUSTER="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=zotero
    - CLUSTER="not @test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - CLUSTER="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - CLUSTER="not @test-cluster-1"

  - stage: release
    install: true
    before_install: true
    script: |-
      if [[ "$TRAVIS_EVENT_TYPE" != "cron" && "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        pip install -r requirements.txt
        npm run build
        npm run release
        # curl --upload-file xpi/zotero-better-bibtex*.xpi https://transfer.sh/zotero-better-bibtex.xpi
      fi
    after_failure: true
