dist: xenial
language: python
python:
  - 3.7

# https://github.com/travis-ci/travis-ci/issues/8920
# https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959
before_install:
  - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
  - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print("blocking:", flags&os.O_NONBLOCK == 0);'
  - sudo add-apt-repository --yes ppa:retorquere/zotero
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install zotero jurism
  - travis_retry ./check-latest-zotero.py

cache:
  npm: true
  bundler: true
  pip: true
  apt: true
  directories:
  - node_modules
  - .cache/pip

script:
  - npm run build
  - ./.travis.py
  - cat behave.ini
  - python3 -c 'import os,sys; os.set_blocking(sys.stdout.fileno(), True)'
  - python3 -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); print("blocking:", flags&os.O_NONBLOCK == 0);'
  - xvfb-run behave

after_failure:
  curl -F "file=@~/.BBTZ5TEST.log" https://file.io

jobs:
  include:
  - stage: test
    env:
    - ZOTERO=zotero
    - CLUSTER="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=zotero
    - CLUSTER="not @test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - CLUSTER="@test-cluster-1"

  - stage: test
    env:
    - ZOTERO=jurism
    - CLUSTER="not @test-cluster-1"

  - stage: release
    install: true
    before_install: true
    script: |-
      if [[ "$TRAVIS_EVENT_TYPE" != "cron" && "$TRAVIS_EVENT_TYPE" != "pull_request" ]]; then
        pip install -r requirements.txt
        npm run build
        npm run release
        # curl --upload-file xpi/zotero-better-bibtex*.xpi https://transfer.sh/zotero-better-bibtex.xpi
      fi
    after_failure: true
