language: ruby
git:
  submodules: false
rvm:
  - 2.1.1
env:
  - TAG=import
  - TAG=export
script: "rake test[$FEATURE]"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm
  - npm install pegjs coffee-script coffee-stir
addons:
  firefox: "30.0"
